// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1QBO9epFvtjR-rQ-2V9kjW_L_dXjIfcs',
    appId: '1:514743040063:web:f340cbdc550e1587c6208a',
    messagingSenderId: '514743040063',
    projectId: 'safepills-a3b1b',
    authDomain: 'safepills-a3b1b.firebaseapp.com',
    storageBucket: 'safepills-a3b1b.firebasestorage.app',
    measurementId: 'G-CJZYFPWJWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJc6tM2tegkX2Rnkapz2mLVUMuuxkqPGQ',
    appId: '1:514743040063:android:bd2659dc69d195d6c6208a',
    messagingSenderId: '514743040063',
    projectId: 'safepills-a3b1b',
    storageBucket: 'safepills-a3b1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNW39RlRKsk8imDmIlJ9hkRAwOy_8sCBY',
    appId: '1:514743040063:ios:cd0c8fca8c107b4ac6208a',
    messagingSenderId: '514743040063',
    projectId: 'safepills-a3b1b',
    storageBucket: 'safepills-a3b1b.firebasestorage.app',
    iosBundleId: 'com.example.safePills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNW39RlRKsk8imDmIlJ9hkRAwOy_8sCBY',
    appId: '1:514743040063:ios:cd0c8fca8c107b4ac6208a',
    messagingSenderId: '514743040063',
    projectId: 'safepills-a3b1b',
    storageBucket: 'safepills-a3b1b.firebasestorage.app',
    iosBundleId: 'com.example.safePills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1QBO9epFvtjR-rQ-2V9kjW_L_dXjIfcs',
    appId: '1:514743040063:web:eecb13cb2f6e88d2c6208a',
    messagingSenderId: '514743040063',
    projectId: 'safepills-a3b1b',
    authDomain: 'safepills-a3b1b.firebaseapp.com',
    storageBucket: 'safepills-a3b1b.firebasestorage.app',
    measurementId: 'G-MZ3Y7Z0NRQ',
  );
}
